# Generated by Django 5.1.5 on 2025-01-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynewapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encryptedfile",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
