# Generated by Django 5.1.5 on 2025-01-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynewapp", "0003_encryptedfile_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedfile",
            name="type",
            field=models.CharField(default="text/", max_length=255),
        ),
    ]
