# Generated by Django 5.1.5 on 2025-01-26 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynewapp", "0004_encryptedfile_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharableLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("expiration", models.DateTimeField()),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mynewapp.encryptedfile",
                        to_field="name",
                    ),
                ),
            ],
        ),
    ]
