# Generated by Django 5.1.5 on 2025-01-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynewapp", "0005_sharablelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharablelink",
            name="user_ids",
            field=models.JSONField(default=list),
        ),
    ]
