# Generated by Django 5.1.5 on 2025-01-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynewapp", "0008_rename_linktype_sharablelink_link_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="encryptedfile",
            name="size",
            field=models.IntegerField(default=0),
        ),
    ]
