version: "3.8"

services:
  frontend:
    build:
      context: ./zephyra_frontend/zephyra
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL={REACT_APP_API_BASE_URL}
      - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
      - REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
      - REACT_APP_AUTH0_CLIENT_SECRET=${REACT_APP_AUTH0_CLIENT_SECRET}
    volumes:
      - ./zephyra_frontend/zephyra:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./zephyra_backend
    ports:
      - "8000:8000"
    volumes:
      - ./zephyra_backend:/app
      - /app/venv

