# Generated by Django 5.1.5 on 2025-01-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mynewapp", "0006_sharablelink_user_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharablelink",
            name="linkType",
            field=models.CharField(default="view", max_length=255),
        ),
    ]
